### ISSUE TITLE
底部任务栏无法遮盖...

### ISSUE THREAD

**Issue by xx299x** [miaomiaosoft/FocusWindowX#2]
![image](https://user-images.githubusercontent.com/23482348/78518916-529d7d80-77f4-11ea-8c02-9657d23809d5.png)
如图所示。
顺便感谢下您，很好用！

**Comment by miaomiaosoft** [comment]
没适配隐藏任务栏的情况
下个版本增加一个参数“底栏隐藏”
启用后将覆盖全屏

**Comment by xx299x** [comment]
> 没适配隐藏任务栏的情况
> 下个版本增加一个参数“底栏隐藏”
> 启用后将覆盖全屏

Ok,谢谢大佬 @miaomiaosoft

**Comment by miaomiaosoft** [comment]
你试试看覆盖是否没问题：
[FocusWindowX.zip](https://github.com/miaomiaosoft/FocusWindowX/files/4443513/FocusWindowX.zip)

我看你应该是WIN10系统，再顺手帮我测试下这个在WIN10上有没有玻璃效果，运行后截图给我，谢谢！
[WIN10毛玻璃亚克力_api.zip](https://github.com/miaomiaosoft/FocusWindowX/files/4443524/WIN10._api.zip)

**Comment by xx299x** [comment]
不对，好了，是可以的！

**Comment by xx299x** [comment]
毛玻璃效果是有的

**Comment by xx299x** [comment]
OK，在隐藏栏自动收起的情况下是有效的

**Comment by miaomiaosoft** [comment]
> 毛玻璃效果是有的

好，但我想知道窗口中显示的数字是几

所以效果是否完美

**Comment by xx299x** [comment]
![image](https://user-images.githubusercontent.com/23482348/78658639-fe31f500-78fc-11ea-9b8f-4d6ae98f7dfa.png)
12

**Comment by miaomiaosoft** [comment]
> ![image](https://user-images.githubusercontent.com/23482348/78658639-fe31f500-78fc-11ea-9b8f-4d6ae98f7dfa.png)
> 12

好的，谢谢
遮罩也没问题吧？

**Comment by xx299x** [comment]
> > ![image](https://user-images.githubusercontent.com/23482348/78658639-fe31f500-78fc-11ea-9b8f-4d6ae98f7dfa.png)
> > 12
> 
> 好的，谢谢
> 遮罩也没问题吧？

是的

**Comment by miaomiaosoft** [comment]
OK
