### ISSUE TITLE
【功能建议】 「重启软件」功能加入菜单；设置禁用启用快捷键

### ISSUE THREAD

**Issue by xx299x** [miaomiaosoft/FocusWindowX#4]
就是在这个菜单中加入「重启软件」功能。
![image](https://user-images.githubusercontent.com/23482348/78684417-ff761880-7922-11ea-8daf-7f8e2a2107ce.png)

还有希望有快速启用/禁用的快捷键

**Comment by miaomiaosoft** [comment]
好，下个版本增加
但由于要重写，可能要晚一点

**Comment by miaomiaosoft** [comment]
已更新
